  
version: "3"
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: learnwp
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
  wordpress:
    image: wordpress:5.6-php7.4-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: docker
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: learnwp
      DEPLOY_ENVIRONMENT: local
      WORDPRESS_DEBUG: 1
      #we need to down and up docker again
      #when add extra config
      #docker-compose down
      #docker-compose up -d
      # WORDPRESS_CONFIG_EXTRA: |
      #   /* direct ftp */
      #   define('FS_METHOD','direct');
      #   define('WP_DEBUG_LOG', true);
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
volumes:
  mysql:
